#!/bin/bash
# PR Manager - Merge Analyzer Script
# Analiza cambios entre ramas antes de merge

set -e

# Colores para output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuración
SOURCE_BRANCH=${1:-""}
TARGET_BRANCH=${2:-"main"}
OUTPUT_FILE="MERGE_ANALYSIS_$(date +%Y%m%d_%H%M%S).md"

if [ -z "$SOURCE_BRANCH" ]; then
    echo -e "${RED}Error: Debe especificar la rama origen${NC}"
    echo "Uso: ./merge-analyzer.sh <rama-origen> [rama-destino]"
    exit 1
fi

echo -e "${BLUE}🔍 PR Manager - Análisis de Merge${NC}"
echo "================================"
echo ""

# Crear archivo de reporte
cat > "$OUTPUT_FILE" << EOF
# 📊 Merge Analysis Report

**Source Branch**: $SOURCE_BRANCH
**Target Branch**: $TARGET_BRANCH
**Analysis Date**: $(date)
**Generated By**: PR Manager Bot

---

## 📈 Resumen del Análisis

EOF

# Verificar si la rama existe
if ! git rev-parse --verify "$SOURCE_BRANCH" > /dev/null 2>&1; then
    echo -e "${RED}❌ Error: La rama '$SOURCE_BRANCH' no existe${NC}"
    exit 1
fi

echo -e "${BLUE}📋 Analizando cambios...${NC}"

# Commits de diferencia
echo "### Commits de Diferencia" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "La rama '$SOURCE_BRANCH' tiene los siguientes commits que no están en '$TARGET_BRANCH':" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "\`\`\`" >> "$OUTPUT_FILE"
git log --oneline --left-right "$TARGET_BRANCH...$SOURCE_BRANCH" >> "$OUTPUT_FILE" || echo "No hay commits de diferencia" >> "$OUTPUT_FILE"
echo "\`\`\`" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Archivos modificados
echo -e "${BLUE}📁 Archivos modificados...${NC}"
echo "### Archivos Modificados" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "| Estado | Archivo |" >> "$OUTPUT_FILE"
echo "|--------|---------|" >> "$OUTPUT_FILE"
git diff --name-status "$TARGET_BRANCH...$SOURCE_BRANCH" | while read line; do
    status=$(echo "$line" | cut -f1)
    file=$(echo "$line" | cut -f2)
    echo "| $status | $file |" >> "$OUTPUT_FILE"
done
echo "" >> "$OUTPUT_FILE"

# Estadísticas
echo -e "${BLUE}📊 Estadísticas...${NC}"
echo "### Estadísticas de Cambios" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
STATS=$(git diff --shortstat "$TARGET_BRANCH...$SOURCE_BRANCH" 2>/dev/null || echo "0 files changed")
echo "- **Cambios**: $STATS" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Análisis de seguridad
echo -e "${BLUE}🔒 Análisis de seguridad...${NC}"
echo "### 🔒 Análisis de Seguridad" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Buscar patrones problemáticos
echo "#### Patrones Detectados" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# SQL Injection patterns
if git diff "$TARGET_BRANCH...$SOURCE_BRANCH" | grep -q "'.*\${" 2>/dev/null; then
    echo -e "${RED}❌ Posible SQL Injection detectado${NC}"
    echo "- 🔴 **CRÍTICO**: Posible SQL Injection (concatenación de strings SQL)" >> "$OUTPUT_FILE"
else
    echo -e "${GREEN}✅ No se detectaron patrones de SQL Injection${NC}"
    echo "- ✅ No se detectaron patrones de SQL Injection" >> "$OUTPUT_FILE"
fi

# console.log
if git diff "$TARGET_BRANCH...$SOURCE_BRANCH" | grep -q "console.log" 2>/dev/null; then
    echo -e "${YELLOW}⚠️ console.log encontrado${NC}"
    echo "- ⚠️ **ADVERTENCIA**: Se encontraron console.log (eliminar antes de producción)" >> "$OUTPUT_FILE"
else
    echo -e "${GREEN}✅ No hay console.log${NC}"
    echo "- ✅ No hay console.log de debugging" >> "$OUTPUT_FILE"
fi

# Hardcoded values
if git diff "$TARGET_BRANCH...$SOURCE_BRANCH" | grep -q "id_Personal = 1" 2>/dev/null; then
    echo -e "${YELLOW}⚠️ Hardcoded user ID${NC}"
    echo "- ⚠️ **ADVERTENCIA**: ID de usuario hardcodeado encontrado" >> "$OUTPUT_FILE"
else
    echo -e "${GREEN}✅ No hay hardcoded IDs${NC}"
    echo "- ✅ No hay IDs hardcodeados" >> "$OUTPUT_FILE"
fi

# TODO/FIXME
if git diff "$TARGET_BRANCH...$SOURCE_BRANCH" | grep -qi "TODO\|FIXME" 2>/dev/null; then
    echo -e "${YELLOW}⚠️ TODO/FIXME encontrado${NC}"
    echo "- ⚠️ **ADVERTENCIA**: Se encontraron comentarios TODO/FIXME" >> "$OUTPUT_FILE"
else
    echo -e "${GREEN}✅ No hay TODOs pendientes${NC}"
    echo "- ✅ No hay TODOs pendientes" >> "$OUTPUT_FILE"
fi

echo "" >> "$OUTPUT_FILE"

# Análisis de dependencias
echo -e "${BLUE}📦 Análisis de dependencias...${NC}"
echo "### 📦 Dependencias" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

if git diff --name-only "$TARGET_BRANCH...$SOURCE_BRANCH" | grep -q "package.json"; then
    echo "Se modificaron dependencias en package.json" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "\`\`\`json" >> "$OUTPUT_FILE"
    git diff "$TARGET_BRANCH...$SOURCE_BRANCH" -- package.json >> "$OUTPUT_FILE"
    echo "\`\`\`" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "**⚠️ Verificar**:" >> "$OUTPUT_FILE"
    echo "- [ ] No hay dependencias vulnerables" >> "$OUTPUT_FILE"
    echo "- [ ] Las versiones son compatibles" >> "$OUTPUT_FILE"
    echo "- [ ] npm audit pasa sin errores críticos" >> "$OUTPUT_FILE"
else
    echo "- ✅ No se modificaron dependencias" >> "$OUTPUT_FILE"
fi

echo "" >> "$OUTPUT_FILE"

# Checklist de merge
echo -e "${BLUE}✅ Checklist de Merge...${NC}"
echo "### ✅ Checklist Pre-Merge" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "- [ ] Código revisado por al menos 1 persona" >> "$OUTPUT_FILE"
echo "- [ ] Tests pasan localmente (npm test)" >> "$OUTPUT_FILE"
echo "- [ ] No hay errores de lint (npm run lint)" >> "$OUTPUT_FILE"
echo "- [ ] La aplicación inicia sin errores (npm start)" >> "$OUTPUT_FILE"
echo "- [ ] No hay vulnerabilidades de seguridad críticas" >> "$OUTPUT_FILE"
echo "- [ ] Documentación actualizada" >> "$OUTPUT_FILE"
echo "- [ ] Commits con mensajes descriptivos" >> "$OUTPUT_FILE"
echo "- [ ] Branch está actualizada con $TARGET_BRANCH" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Verificación de conflictos
echo -e "${BLUE}🔀 Verificando conflictos...${NC}"
echo "### 🔀 Estado de Conflictos" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

if git merge-tree $(git merge-base "$TARGET_BRANCH" "$SOURCE_BRANCH") "$TARGET_BRANCH" "$SOURCE_BRANCH" | grep -q "changed in both"; then
    echo -e "${RED}❌ Hay conflictos potenciales${NC}"
    echo "- 🔴 **CONFLICTOS DETECTADOS**: Requiere resolución manual" >> "$OUTPUT_FILE"
    git merge-tree $(git merge-base "$TARGET_BRANCH" "$SOURCE_BRANCH") "$TARGET_BRANCH" "$SOURCE_BRANCH" | grep "changed in both" >> "$OUTPUT_FILE"
else
    echo -e "${GREEN}✅ Sin conflictos${NC}"
    echo "- ✅ No hay conflictos detectados" >> "$OUTPUT_FILE"
fi

echo "" >> "$OUTPUT_FILE"

# Recomendación final
echo -e "${BLUE}📝 Generando recomendación...${NC}"
echo "### 📝 Recomendación" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Determinar estado
HAS_ERRORS=false
if git diff "$TARGET_BRANCH...$SOURCE_BRANCH" | grep -q "'.*\${" 2>/dev/null; then
    HAS_ERRORS=true
fi

if [ "$HAS_ERRORS" = true ]; then
    echo -e "${RED}❌ NO APROBADO PARA MERGE${NC}"
    echo "**Estado**: 🔴 **NO APROBADO**" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "Se detectaron problemas críticos que deben corregirse antes del merge." >> "$OUTPUT_FILE"
else
    echo -e "${GREEN}✅ APROBADO PARA MERGE${NC}"
    echo "**Estado**: 🟢 **APROBADO**" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "La rama está lista para merge. Por favor verificar el checklist antes de proceder." >> "$OUTPUT_FILE"
fi

echo "" >> "$OUTPUT_FILE"
echo "---" >> "$OUTPUT_FILE"
echo "*Reporte generado por PR Manager - $(date)*" >> "$OUTPUT_FILE"

echo ""
echo -e "${GREEN}✅ Análisis completado${NC}"
echo "📄 Reporte guardado en: $OUTPUT_FILE"
echo ""
echo "Para ver el reporte completo:"
echo "  cat $OUTPUT_FILE"
